### ISSUE TITLE
Is PG15 Supported

### ISSUE THREAD

**Issue by luss** [pgsql-io/multicorn2#18]
PG 15 is presently at Beta4 and is expected to be RC & then GA in the next month or two.  Does Multicorn2 support it?

**Comment by luss** [comment]
Yes, it's a work in process.  Affan Salman is a new committer for this project and he has checked in a fix that allows us to build cleanly for PG15.  I have tagged v2.4 that includes Affan's commit plus the work that Shaheed has been doing.  Let the testing begin!!

**Comment by devrimgunduz** [comment]
Any updates?

**Comment by wieck** [comment]
I can test this once I am back home next week.

**Comment by luss** [comment]
YES.  It is supported.   And...  I'd love to see Jan do some more testing.
:-)

**Comment by luss** [comment]
For this multicorn2 project, pg15 works as good as pg14 does.   They both have a performance regression that hasn't been found yet.  Pieces of the WHERE clause are not being pushed down in some cases they were in pg12 & pg13 in the original multicorn project.

**Comment by ShaheedHaque** [comment]
> For this multicorn2 project, pg15 works as good as pg14 does.

Given that, can a release be cut please?

**Comment by Ank1l** [comment]
Still While installing on PG15  Multicorn2, We got ERROR:  Error in python: ModuleNotFoundError
DETAIL:  No module named 'multicorn'
please help me

**Comment by Ank1l** [comment]
@luss Not the above error is resolved but a new error is coming: 
ERROR:  Error in python: AttributeError
DETAIL:  module 'multicorn' has no attribute 'get_class'
SQL state: XX000

**Comment by ShaheedHaque** [comment]
Try looking in your PG server log. It may contain a stack trace that will be helpful

**Comment by ShaheedHaque** [comment]
> @luss Not the above error is resolved but a new error is coming:
> ERROR: Error in python: AttributeError
> DETAIL: module 'multicorn' has no attribute 'get_class'
> SQL state: XX000

I've just hit this error too...

**Comment by luss** [comment]
Pg15 is supported so I am closing this issue.   A specific installation problem in one environment should be opened as a specific siiue.
