### ISSUE TITLE
Example and Steps required for installing it with third-party e.g s3csv_fdw

### ISSUE THREAD

**Issue by shhnwz** [pgsql-io/multicorn2#36]
Looking of steps to include s3csv_fdw (third-party)

**Comment by ShaheedHaque** [comment]
As per the [README](https://github.com/pgsql-io/multicorn2?tab=readme-ov-file#download--compile-multicorn2-1), just try "sudo make install".

As indicated, this will both install the compiled code as a Postgres extension library , and also the Python files needed by your 3rd party Python FDW.
