### ISSUE TITLE
Python-side FDW debugging made near-impossible by missing "log_to_postgres"

### ISSUE THREAD

**Issue by ShaheedHaque** [pgsql-io/multicorn2#37]
Generally, debugging the Python-side of an FDW needs to be able to produce user-visible output. This used to be possible using `log_to_postgres`, but I just noticed that this is missing.

After a bit of digging, it is clear that this was caused (by me!) in #28 by accidentally deleting the line which caused the relevant module built from `utils.c`.

**Comment by shanness** [comment]
Thanks for such a great project!  I still can't get any logging out :( (only exceptions end up in the log).

**Comment by ShaheedHaque** [comment]
I'm not sure what to advise. From what I remember, everything ended up in the postgres main log file. Maybe double check the message is emitted by the running code, and you have the right multicorn version installed?
