### ISSUE TITLE
Can you add support for pg14?

### ISSUE THREAD

**Issue by denishpatel** [pgsql-io/multicorn2#4]

**Comment by luss** [comment]
Now this issue is properly with the multicorn2 project and I am working on debugging the pushdown iussue in pg14 today.

**Comment by denishpatel** [comment]
@luss Let me know if you need help with testing.

**Comment by luss** [comment]
Hey Guys,  please test some more with v2.2.  It now supports pushdown and is tested in pg13 & pg14 with python3.6

**Comment by olirice** [comment]
```
```

**Comment by luss** [comment]
:-)
