### ISSUE TITLE
Plans to publish this library on pypi.org?

### ISSUE THREAD

**Issue by whummer** [pgsql-io/multicorn2#61]
First of all, big kudos and thanks for providing this library - it's really useful to connect custom data sources into Postgres! 🚀 

Are there any plans to publish this library on [pypi.org](https://pypi.org/)? Wasn't able to find an entry, as [this](https://pypi.org/project/multicorn/) seems to be a different project. This would allow users to install the Python package via `pip install ...` (or also using other Python packaging frameworks like `poetry`, etc), and would make it much easier for other Python projects to consume this library.

Since everything is already configured in `pyproject.toml`/`setup.py`, it would probably not be too much effort to achieve. (simply uploading the package with a tool like `twine`).

Thanks for your help! 🙌  /cc @luss @mfenniak

**Comment by ShaheedHaque** [comment]
See the discussion in #56. It is more work than for a "normal" package...

**Comment by whummer** [comment]
Thanks for the pointer @ShaheedHaque  - sorry, missed the item in the Github Discussions section. Closing this one, let's continue the conversation over there! 👍
